name: 🐞 Relatório de bug
description: Registre um relatório de bug
title: "[Bug]: "
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por nos avisar sobre algo que pode melhorar!
  - type: textarea
    id: what-happened
    attributes:
      label: O que aconteceu?
      description: Informe também o que você esperava que acontecesse e como reproduzir o problema.
      placeholder: Descreva o que você está vendo.
      value: "Ocorreu um bug."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Saída de log relevante
      description: Copie e cole qualquer saída de log relevante. Ela será formatada automaticamente como código, então não é preciso usar crases.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar esta issue, você concorda em seguir nosso [Código de Conduta](https://github.com/google-agentic-commerce/AP2?tab=coc-ov-file#readme)
      options:
        - label: Concordo em seguir o Código de Conduta deste projeto
          required: true
