name: 💡 Solicitação de funcionalidade
description: Sugira uma ideia para este repositório
title: "[Feat]: "
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por nos avisar sobre algo que pode melhorar!
  - type: textarea
    id: problem
    attributes:
      label: A sua solicitação está relacionada a um problema? Descreva.
      description: Uma descrição clara e concisa do problema.
      placeholder: "Ex.: sempre tenho dificuldade quando [...]"
  - type: textarea
    id: describe
    attributes:
      label: Descreva a solução que você gostaria
      description: Uma descrição clara e concisa do que você quer que aconteça.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Descreva as alternativas que você considerou
      description: Uma descrição clara e concisa de soluções ou funcionalidades alternativas que você considerou.
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Adicione aqui qualquer outro contexto ou captura de tela sobre a solicitação.
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar esta issue, você concorda em seguir nosso [Código de Conduta](https://github.com/google-agentic-commerce/AP2?tab=coc-ov-file#readme)
      options:
        - label: Concordo em seguir o Código de Conduta deste projeto
          required: true
