# -*- coding: utf-8 -*-
"""Backlog das evoluções v3–v6 do ambiente de homologação do AP2.

Estrutura: Épico -> Feature -> PBI -> Task. Estimativas são sugestões.
"""

REPO = "ds-fabiopinheiro/ap2-protocol"

# ---------------------------------------------------------------------------
# Feature de ambiente, repetida em cada versão
# ---------------------------------------------------------------------------

def env_feature(v, base, fid, space_extra=None, vercel=False, first=False):
    branch = f"homolog-{v}"
    space = f"ds-fabiopinheiro/ap2-homolog-{v}"
    pbis = []
    tasks = [
        ("Infra", f"Criar o branch {branch} a partir de {base}",
         f"Criar {branch} a partir do último commit de {base} e proteger o branch (PR obrigatório, sem push direto).",
         f"{branch} existe no GitHub, com regra de proteção ativa.", 1),
        ("Infra", f"Criar o Space {space} (Docker, CPU Basic, Protected)",
         f"Criar o Space com o mesmo Dockerfile da v2 e o build arg AP2_REF={branch}. Cadastrar as variáveis AGENT_MODEL, SUPABASE_URL e AP2_ENV={v}. Os secrets (GOOGLE_API_KEY, SUPABASE_SECRET_KEY) são cadastrados pelo dono da conta.",
         "Space em estado Running, com AP2_ENV e AP2_REF corretos nos logs de inicialização.", 3),
        ("Infra", f"Incluir o mapeamento {branch} → {space} no workflow de rebuild",
         "Alterar .github/workflows/hf-space-rebuild.yml para reconstruir o Space correspondente ao branch do push. O token HF_TOKEN precisa de permissão de escrita no novo Space (ação do dono da conta).",
         f"Push de backend em {branch} dispara Factory rebuild só de {space}; push em homolog-deploy continua reconstruindo só a v2.", 3),
        ("QA", f"Verificar que as versões anteriores continuam funcionando após a criação da {v}",
         f"Executar o roteiro de regressão da v2 (agent card público, compra autônoma com price drop e restore após restart) e o roteiro de aceite de cada versão anterior à {v}.",
         "Roteiro executado com evidências (prints e consultas SQL) anexadas à issue.", 3),
        ("Docs", f"Registrar a {v} no CLAUDE.md e no deploy/README.md",
         f"Documentar branch, Space, variáveis, rotas públicas, limitações e o resultado dos testes da {v}.",
         "Documentação revisada em PR para o branch da versão.", 2),
    ]
    if first:
        tasks.insert(2, ("Back", "Isolar o estado de cada versão no Supabase (AP2_ENV)",
            "Criar migration aditiva com as tabelas ap2_env_state_files, ap2_env_mandates e ap2_env_events (coluna environment na chave). Alterar sync_supabase.py para usar essas tabelas quando AP2_ENV estiver definido. As tabelas da v2 não mudam. A migration precisa chegar ao homolog-deploy, porque a integração do Supabase só aplica migrations desse branch.",
            "Com AP2_ENV=v3, restore e watch leem e gravam só linhas com environment='v3'; a v2 continua usando ap2_state_files sem alteração; Security Advisor sem novos alertas.", 8))
        tasks.insert(3, ("Infra", "Aplicar a migration de isolamento no projeto ap2-homolog-db",
            "Mesclar só a migration em homolog-deploy (PR separado) para a integração do Supabase aplicá-la. Conferir a aplicação no painel.",
            "Tabelas ap2_env_* criadas, RLS ligado, sem privilégios para anon e authenticated.", 2))
    if vercel:
        tasks.insert(2, ("Infra", f"Criar o projeto Vercel ap2-homolog-{v}-frontend",
            f"Novo projeto apontando para code/web-client, branch de produção {branch}, com as variáveis VITE_* da versão. Um projeto por versão mantém a URL pública sem login, porque URLs de preview exigem login na proteção padrão do Vercel.",
            f"https://ap2-homolog-{v}-frontend.vercel.app abre sem login e mostra a versão {v}.", 3))
    if space_extra:
        tasks.extend(space_extra)
    rn = [
        f"RN01 – Todo trabalho da {v} entra por PR no branch {branch}; o branch {base} não recebe código da {v}.",
        f"RN02 – O estado da {v} no Supabase fica separado das outras versões (AP2_ENV={v}).",
        "RN03 – Nenhum segredo é gravado no repositório, em variável VITE_* ou em variável pública do Space.",
    ]
    criterios = [
        f"O Space {space} fica em estado Running a partir do branch {branch}.",
        f"Um push de backend em {branch} reconstrói apenas {space}.",
        f"Após restart do Space da {v}, o log mostra restore apenas de arquivos com environment='{v}'.",
        "A v2 (homolog-deploy) e as versões anteriores passam no roteiro de regressão depois da criação da nova versão.",
        "Se o secret GOOGLE_API_KEY estiver ausente, o log de inicialização mostra o aviso e o agent card continua respondendo.",
    ]
    if vercel:
        criterios.insert(2, f"A URL https://ap2-homolog-{v}-frontend.vercel.app abre sem login.")
    pbis.append(dict(
        id=f"{fid}.1", title=f"Ambiente de homologação {v} publicado a partir do branch {branch}",
        como="responsável pela homologação", quero=f"um ambiente próprio da {v}, separado da versão anterior",
        para=f"validar a {v} sem alterar o que já está publicado",
        contexto=f"Cada evolução ganha um branch ({branch}), um Space no Hugging Face e, quando houver mudança de tela, um projeto no Vercel. A versão anterior continua disponível para comparação.",
        rns=rn, fora=["Domínio próprio (fora de *.hf.space e *.vercel.app).", "Alteração de plano ou hardware no HF, Vercel ou Supabase."],
        criterios=criterios, pts=8 if first else 5, deps=[] , tasks=tasks))
    return dict(
        id=fid, title=f"Ambiente e branch da {v}",
        problema=f"A {v} precisa de um ambiente público próprio. Hoje só existe o ambiente da v2 (homolog-deploy).",
        solucao=f"Branch {branch} derivado de {base}, Space {space}" + (", projeto Vercel próprio" if vercel else "") + " e estado isolado no Supabase por AP2_ENV.",
        usuarios="Responsável pela homologação; pessoas que validam pelo link.",
        rns=rn, fora=["Promoção automática entre versões."],
        deps=["Secret HF_TOKEN com permissão no novo Space (ação do dono da conta).", "Secrets do Space cadastrados pelo dono da conta."],
        criterios=criterios[:3], pbis=pbis)


# ---------------------------------------------------------------------------
# Épicos
# ---------------------------------------------------------------------------

EPICS = []

# ============================ v3 — Merchant Agent ==========================
EPICS.append(dict(
    id="EP-V3", version="v3", branch="homolog-v3", base="homolog-deploy",
    title="v3 · Merchant Agent e Merchant Payment Processor Agent publicados via A2A",
    contexto=("Na v2 o papel de Merchant é um servidor MCP com lógica fixa (merchant_agent_mcp). O repositório também tem o "
              "Merchant Agent (roles/merchant_agent, porta 8001) e o Merchant Payment Processor Agent (roles/merchant_payment_processor_agent, "
              "porta 8003), agentes A2A com LLM usados no cenário human-present/cards. Nenhum dos dois está publicado."),
    objetivo=("Publicar os dois agentes do lado do comerciante como serviços A2A no ambiente v3, com agent card público do Merchant Agent, "
              "para servir de base à v4 (Shopping Agent v1) e permitir validar o Merchant Agent isoladamente."),
    incluido=["Branch homolog-v3 e Space ap2-homolog-v3.", "Isolamento do estado por versão no Supabase (AP2_ENV).",
              "Merchant Agent com rota pública /a2a/merchant_agent e limite de requisições.",
              "Merchant Payment Processor Agent acessível só dentro do container.",
              "Modelo dos agentes A2A configurável por AGENT_MODEL (hoje fixo no código).",
              "Script de teste A2A e roteiro de QA."],
    excluido=["Shopping Agent v1 e Credentials Provider Agent (v4).", "Tela no web client (v5).", "Agentes em Go (v6)."],
    metrica=["Agent card do Merchant Agent respondendo publicamente (HTTP 200).",
             "Script de teste A2A concluído com resposta assinada pelo Merchant em 3 execuções seguidas.",
             "Pico de RPM do Gemini no teste abaixo de 15."],
    dependencias=["GOOGLE_API_KEY com cota disponível (plano gratuito: 15 RPM, 500 RPD, compartilhado entre Spaces).",
                  "Resposta do caso de faturamento Google OR_CCR_53 (prevista até 03/10/2026) para decidir plano pago."],
    riscos=["A cota do Gemini é compartilhada entre v2 e v3 se usarem a mesma chave.",
            "O README do cenário human-present ainda cita IntentMandate/CartMandate (vocabulário da v0.1); o código usa checkout_mandate/payment_mandate. Validar o comportamento real antes de escrever os testes.",
            "No teste de 27/09/2026 (PR #5), o Gemini respondeu 503 UNAVAILABLE e, em outra sessão, o modelo chamou como função o nome de um JSON do prompt (product_preview_unavailable). Os agentes A2A da v3 usam o mesmo modelo e estão sujeitos aos dois erros."],
    premissas=["Os agentes human-present funcionam no mesmo container da v2 sem conflito de portas (8001–8003 vs 8080–8083).",
               "Free tier do HF permite mais um Space CPU Basic."],
    features=[
        env_feature("v3", "homolog-deploy", "F-V3.1", first=True),
        dict(id="F-V3.2", title="Merchant Agent publicado como serviço A2A",
             problema="O Merchant Agent (roles/merchant_agent) só roda localmente na porta 8001, sem acesso público.",
             solucao="Subir o Merchant Agent no container da v3, expor /a2a/merchant_agent pelo nginx com limite de requisições e agent card com URL pública.",
             usuarios="Desenvolvedores e integradores que validam a comunicação A2A com o Merchant.",
             rns=["RN01 – O Merchant Agent usa o modelo definido em AGENT_MODEL.",
                  "RN02 – A rota pública /a2a/merchant_agent tem limite de 20 requisições/min por visitante.",
                  "RN03 – As respostas do Merchant com opções de compra são assinadas com a chave do Merchant."],
             fora=["Catálogo real de produtos.", "Autenticação de chamadores."],
             deps=["F-V3.1 concluída."],
             criterios=["GET /a2a/merchant_agent/.well-known/agent-card.json retorna 200 com a URL pública do Space.",
                        "Uma requisição A2A de busca de produto retorna opções assinadas pelo Merchant.",
                        "Com a mesma configuração da v2 (20 req/min, rajada de 10), a partir da 12ª requisição simultânea do mesmo visitante a resposta é 429 em JSON."],
             pbis=[
                 dict(id="F-V3.2.1", title="Merchant Agent acessível por A2A com agent card público",
                      como="integrador de agentes", quero="chamar o Merchant Agent por uma URL pública",
                      para="validar a comunicação A2A com o comerciante sem instalar nada",
                      contexto="O agente sobe hoje com `python -m roles.merchant_agent` na porta 8001 (common/server.py). O agent card traz URL localhost.",
                      rns=["RN01 – A URL do agent card é reescrita para https://$SPACE_HOST/a2a/merchant_agent na inicialização.",
                           "RN02 – Limite de 20 requisições/min por visitante e 120/min no total na rota /a2a/merchant_agent."],
                      fora=["Mudança de comportamento do agente."],
                      criterios=["O agent card público retorna 200 e o campo url aponta para o Space da v3.",
                                 "Se o Merchant Agent cair, o container reinicia (mesmo comportamento da v2).",
                                 "Requisições acima do limite recebem 429 com corpo JSON e cabeçalho CORS.",
                                 "A rota /a2a/shopping_agent da v2 continua funcionando no Space da v3."],
                      pts=5, deps=["F-V3.1.1"],
                      tasks=[
                          ("Back", "Iniciar o Merchant Agent no start.sh da v3",
                           "Adicionar start_service merchant-agent com `python -m roles.merchant_agent`, com LOGS_DIR e TEMP_DB_DIR da versão.",
                           "Log mostra o Merchant Agent em 127.0.0.1:8001 e o agent card local responde.", 3),
                          ("Back", "Reescrever a URL do agent card do Merchant Agent",
                           "Aplicar ao agent.json do merchant_agent a mesma reescrita usada no shopping_agent_v2 (AP2_PUBLIC_BASE_URL).",
                           "Card público com url https://ds-fabiopinheiro-ap2-homolog-v3.hf.space/a2a/merchant_agent.", 2),
                          ("Infra", "Adicionar a rota /a2a/merchant_agent no nginx com limite de requisições",
                           "Nova location com proxy para 127.0.0.1:8001, proxy_buffering off e as zonas limit_req existentes.",
                           "curl no agent card retorna 200; 35 requisições simultâneas geram 429 a partir do limite.", 3),
                          ("QA", "Testar agent card, limite e reinício do Merchant Agent",
                           "Executar os critérios de aceite e anexar evidências.", "Critérios verificados com evidências na issue.", 3),
                      ]),
                 dict(id="F-V3.2.2", title="Busca de produto no Merchant Agent com resposta assinada",
                      como="integrador de agentes", quero="enviar um pedido de produto ao Merchant Agent e receber as opções assinadas",
                      para="confirmar que o Merchant da v3 segue o AP2 antes de ligar o Shopping Agent v1",
                      contexto="No cenário human-present o Shopping Agent v1 envia a intenção de compra ao Merchant Agent, que devolve as opções de carrinho assinadas.",
                      rns=["RN01 – O teste usa só mensagens A2A com a extensão AP2 (EXTENSION_URI).",
                           "RN02 – O teste falha se a assinatura do Merchant não verificar com a chave pública publicada."],
                      fora=["Pagamento (coberto na v4)."],
                      criterios=["O script de teste envia a intenção de compra e recebe pelo menos uma opção assinada.",
                                 "O script verifica a assinatura e imprime OK.",
                                 "Com assinatura alterada, o script imprime FALHA e sai com código diferente de zero.",
                                 "Os mandates gerados aparecem em ap2_env_mandates com environment='v3'."],
                      pts=5, deps=["F-V3.2.1"],
                      tasks=[
                          ("QA", "Escrever script de teste A2A para o Merchant Agent",
                           "Script Python (a2a-sdk) em deploy/tests/ que envia a intenção, recebe as opções e verifica a assinatura.",
                           "Script executa contra o Space v3 e retorna código 0 no caminho feliz.", 8),
                          ("Back", "Levar o watch.log dos agentes para LOGS_DIR",
                           "Garantir que o log de comunicação A2A (common/watch_log.py) fica em LOGS_DIR e aparece nos logs do Space.",
                           "Requisição de teste aparece no log com método, URL e mandates.", 2),
                          ("Back", "Registrar no Supabase os mandates emitidos pelo Merchant Agent",
                           "Identificar onde o Merchant Agent persiste os mandates e incluí-los no espelhamento do sync (AP2_ENV).",
                           "Linhas em ap2_env_mandates após o teste.", 5),
                          ("QA", "Executar o teste 3 vezes e medir o consumo do Gemini",
                           "Rodar o script 3 vezes e registrar RPM/TPM/RPD do AI Studio.", "Consumo registrado na issue; pico abaixo de 15 RPM.", 2),
                      ]),
             ]),
        dict(id="F-V3.3", title="Merchant Payment Processor Agent e modelo configurável nos agentes A2A",
             problema="O Processor Agent não está publicado e os agentes A2A do cenário human-present usam o modelo gemini-3.1-flash-lite-preview fixo no código (common/function_call_resolver.py).",
             solucao="Subir o Processor Agent na porta 8003, só interna, e fazer os agentes A2A lerem o modelo de AGENT_MODEL, com a mesma regra da v2 (LiteLLM quando houver prefixo de provedor).",
             usuarios="Responsável pela homologação (troca de modelo sem alterar código).",
             rns=["RN01 – A porta 8003 não é exposta pelo nginx.",
                  "RN02 – Sem AGENT_MODEL, o modelo padrão continua gemini-3.1-flash-lite-preview."],
             fora=["Exposição pública do Processor Agent."],
             deps=["F-V3.1 concluída."],
             criterios=["O Processor Agent responde em 127.0.0.1:8003 dentro do container.",
                        "Uma requisição externa para /a2a/merchant_payment_processor_agent recebe 404.",
                        "Com AGENT_MODEL alterado, o log dos agentes A2A mostra o novo modelo."],
             pbis=[
                 dict(id="F-V3.3.1", title="Merchant Payment Processor Agent em execução interna com desafio OTP",
                      como="Shopping Agent v1 (v4)", quero="que o Processor Agent esteja disponível dentro do container",
                      para="processar o pagamento com desafio OTP no cenário assistido",
                      contexto="O Processor Agent pede OTP ao usuário (valor de demo 123) antes de concluir o pagamento (merchant_payment_processor_agent/tools.py).",
                      rns=["RN01 – Acesso apenas por 127.0.0.1:8003.", "RN02 – O OTP de demonstração é 123."],
                      fora=["OTP real por SMS ou e-mail."],
                      criterios=["O agent card local em 127.0.0.1:8003 responde 200.",
                                 "Uma requisição externa ao Processor recebe 404.",
                                 "Se o Processor cair, o container reinicia."],
                      pts=3, deps=["F-V3.1.1"],
                      tasks=[
                          ("Back", "Iniciar o Processor Agent no start.sh da v3",
                           "start_service com `python -m roles.merchant_payment_processor_agent` e espera pelo agent card local.",
                           "Log mostra o Processor Agent em 127.0.0.1:8003.", 2),
                          ("QA", "Verificar isolamento e reinício do Processor Agent",
                           "curl externo recebe 404; kill do processo reinicia o container.", "Evidências anexadas.", 2),
                      ]),
                 dict(id="F-V3.3.2", title="Modelo dos agentes A2A definido por AGENT_MODEL",
                      como="responsável pela homologação", quero="trocar o modelo dos agentes A2A pela variável AGENT_MODEL",
                      para="usar outro provedor (ex.: Vercel AI Gateway) se a cota do Gemini acabar",
                      contexto="common/function_call_resolver.py chama generate_content com o modelo fixo gemini-3.1-flash-lite-preview; o Shopping Agent v2 já lê AGENT_MODEL.",
                      rns=["RN01 – Sem '/' no nome: cliente Gemini nativo.", "RN02 – Com prefixo de provedor: LiteLLM.",
                           "RN03 – O comportamento da v2 não muda.",
                           "RN04 – Erro temporário do modelo (503/UNAVAILABLE) tem até 2 novas tentativas com espera crescente, com a mesma regra adotada na v2 após o teste do PR #5; erro 400 e erro de ferramenta não são repetidos."],
                      fora=["Parâmetros de geração (temperatura, tokens)."],
                      criterios=["Com AGENT_MODEL=gemini-3.1-flash-lite-preview, o teste de F-V3.2.2 passa.",
                                 "Com AGENT_MODEL de outro provedor e a chave correspondente, o teste de F-V3.2.2 passa.",
                                 "Com AGENT_MODEL inválido, o log mostra erro claro e o agent card continua respondendo.",
                                 "Com um 503 simulado na primeira chamada ao modelo, a requisição é concluída na nova tentativa.",
                                 "Com 503 simulado em todas as chamadas, a resposta traz erro legível após 2 novas tentativas."],
                      pts=5, deps=["F-V3.2.2"],
                      tasks=[
                          ("Back", "Ler AGENT_MODEL em function_call_resolver.py e base_server_executor.py",
                           "Substituir o modelo fixo pela variável; para nomes com prefixo, usar LiteLLM (mesma regra de _resolve_model da v2).",
                           "Testes unitários cobrindo os dois caminhos.", 8),
                          ("Back", "Aplicar a regra de nova tentativa em erro 503 nos agentes A2A",
                           "Reusar a implementação de retry adotada na v2 (PR de backend após o teste do PR #5) em base_server_executor.py/function_call_resolver.py.",
                           "Teste unitário com 503 simulado cobrindo sucesso na nova tentativa e esgotamento.", 5),
                          ("QA", "Testar a troca de modelo e a nova tentativa nos agentes A2A",
                           "Executar os 5 critérios de aceite.", "Evidências anexadas.", 3),
                      ]),
             ]),
    ]))

# ============================ v4 — Shopping Agent v1 =======================
EPICS.append(dict(
    id="EP-V4", version="v4", branch="homolog-v4", base="homolog-v3",
    title="v4 · Shopping Agent v1 e Credentials Provider Agent com jornada assistida no ADK Web",
    contexto=("O Shopping Agent v1 (roles/shopping_agent) é um agente coordenador com sub-agentes (shopper, shipping_address_collector, "
              "payment_method_collector) que conversa com Merchant, Credentials Provider e Processor por A2A. É o agente do cenário "
              "human-present/cards, em que o usuário confirma carrinho, endereço, forma de pagamento e OTP. No repositório ele roda com "
              "`adk web` (tela de desenvolvimento do ADK, porta 8000)."),
    objetivo="Publicar o cenário human-present/cards completo na v4, com o usuário executando a compra assistida pelo ADK Web.",
    incluido=["Branch homolog-v4 e Space ap2-homolog-v4.", "Credentials Provider Agent (porta 8002, interno).",
              "Shopping Agent v1 acessível pelo ADK Web, restrito a esse agente.", "Roteiro de compra assistida ponta a ponta.",
              "Registro dos mandates da jornada assistida no Supabase."],
    excluido=["Tela da jornada assistida no web client React (v5).", "Agentes em Go (v6)."],
    metrica=["Compra assistida concluída pelo ADK Web em 3 execuções seguidas, com OTP 123.",
             "Payment Mandate assinado pelo usuário registrado em ap2_env_mandates (environment='v4').",
             "Pico de RPM abaixo de 15 durante uma compra assistida."],
    dependencias=["Épico v3 concluído (Merchant e Processor Agents).", "Cota do Gemini: 4 agentes com LLM por compra."],
    riscos=["O ADK Web é uma tela de desenvolvimento: lista todos os agentes do diretório e expõe a API do ADK. Precisa de diretório dedicado e limite de requisições.",
            "Consumo do Gemini maior que na jornada autônoma (Shopping Agent v1 e 3 agentes remotos chamam o modelo)."],
    premissas=["O ADK Web funciona atrás do nginx em um subcaminho ou em porta dedicada exposta pelo nginx; a forma será definida na task de spike.",
               "Os endereços localhost:8001/8002 fixos em remote_agents.py continuam válidos porque todos os agentes rodam no mesmo container.",
               "O Shopping Agent v1 e seus 3 sub-agentes já usam common/retrying_llm_agent.py (RetryingLlmAgent) com max_retries=5: até 5 tentativas (4 novas), repetindo o turno inteiro do agente em qualquer exceção, sem espera. Precisa seguir a regra de retry da v2 (RN04 de F-V3.3.2), que repete só a chamada ao modelo em 503."],
    features=[
        env_feature("v4", "homolog-v3", "F-V4.1"),
        dict(id="F-V4.2", title="Credentials Provider Agent publicado internamente",
             problema="O Credentials Provider Agent (roles/credentials_provider_agent) não está publicado; sem ele o Shopping Agent v1 não lista formas de pagamento nem obtém a credencial.",
             solucao="Subir o agente na porta 8002, só interna, com a conta de demonstração do repositório (account_manager.py).",
             usuarios="Shopping Agent v1.",
             rns=["RN01 – Acesso apenas por 127.0.0.1:8002.", "RN02 – Só dados fictícios de demonstração."],
             fora=["Carteira real ou cartão real."], deps=["F-V4.1 concluída."],
             criterios=["O agent card local em 127.0.0.1:8002 responde 200.", "Requisição externa recebe 404."],
             pbis=[dict(id="F-V4.2.1", title="Credentials Provider Agent lista as formas de pagamento da conta de demonstração",
                        como="usuário da jornada assistida", quero="ver as formas de pagamento da conta de demonstração",
                        para="escolher com qual pagar",
                        contexto="O agente guarda a carteira de demonstração em account_manager.py (cartão tokenizado DPAN).",
                        rns=["RN01 – Só a conta de demonstração é retornada."], fora=["Cadastro de novas formas de pagamento."],
                        criterios=["Uma requisição A2A interna retorna a lista de formas de pagamento da demo.",
                                   "Com o agente parado, o Shopping Agent v1 informa que não foi possível obter as formas de pagamento."],
                        pts=3, deps=["F-V4.1.1"],
                        tasks=[("Back", "Iniciar o Credentials Provider Agent no start.sh da v4",
                                "start_service com `python -m roles.credentials_provider_agent`.", "Agent card local responde.", 2),
                               ("Back", "Incluir os arquivos do Credentials Provider no espelhamento do Supabase",
                                "Mapear onde o agente grava estado e garantir restore/watch com AP2_ENV=v4.", "Restart mantém o estado.", 3),
                               ("QA", "Testar a listagem e a falha do Credentials Provider", "Executar os critérios.", "Evidências anexadas.", 2)])]),
        dict(id="F-V4.3", title="Compra assistida com o Shopping Agent v1 no ADK Web",
             problema="Não há como executar a jornada human-present pelo link de homologação.",
             solucao="Publicar o ADK Web restrito ao Shopping Agent v1, com limite de requisições, e validar a compra assistida ponta a ponta.",
             usuarios="Pessoas que validam a jornada assistida pelo link.",
             rns=["RN01 – O ADK Web mostra apenas o shopping_agent (v1).",
                  "RN02 – O usuário confirma carrinho, forma de pagamento e Payment Mandate antes do pagamento.",
                  "RN03 – O pagamento só é concluído com o OTP de demonstração 123."],
             fora=["Tela React da jornada assistida (v5)."], deps=["F-V4.2 concluída.", "Épico v3 concluído."],
             criterios=["A URL pública do ADK Web abre e lista só o shopping_agent.",
                        "A compra assistida termina com recibo exibido na conversa.",
                        "Com OTP diferente de 123, o pagamento não é concluído e a conversa informa o erro."],
             pbis=[
                 dict(id="F-V4.3.1", title="Spike: forma de publicar o ADK Web atrás do nginx",
                      como="time de desenvolvimento", quero="decidir como expor o ADK Web (porta 8000) no Space",
                      para="publicar a jornada assistida sem expor outros agentes nem a API de desenvolvimento sem limite",
                      contexto="`adk web` serve a tela em /dev-ui e a API do ADK na mesma porta. O Space tem uma porta pública (7860).",
                      rns=["RN01 – Resultado registrado como decisão no CLAUDE.md, com alternativas avaliadas."],
                      fora=["Implementação completa (PBI seguinte)."],
                      criterios=["Documento de decisão com pelo menos 2 alternativas, riscos e a escolhida.",
                                 "Prova de conceito da alternativa escolhida abrindo /dev-ui pelo Space."],
                      pts=3, deps=["F-V4.1.1"],
                      tasks=[("Back", "Testar ADK Web em subcaminho e em diretório de agentes dedicado",
                              "Avaliar `adk web` com diretório contendo só o shopping_agent e acesso via nginx.", "Prova de conceito funcionando.", 5),
                             ("Docs", "Registrar a decisão sobre o ADK Web", "Seção no CLAUDE.md com alternativas e riscos.", "Decisão revisada.", 2)]),
                 dict(id="F-V4.3.2", title="Compra assistida ponta a ponta pelo ADK Web",
                      como="pessoa que valida a jornada assistida", quero="comprar um produto confirmando cada etapa",
                      para="comparar a jornada assistida com a autônoma da v2",
                      contexto="Fluxo do README do cenário: pedido → opções do Merchant → seleção → vínculo do Credentials Provider → forma de pagamento → Payment Mandate assinado → OTP → recibo.",
                      rns=["RN01 – Cada etapa exige confirmação do usuário.", "RN02 – OTP de demonstração 123.",
                           "RN03 – Os mandates da jornada são registrados com environment='v4'."],
                      fora=["Endereço real de entrega."],
                      criterios=["Cenário: compra concluída — Dado o ADK Web aberto, Quando o usuário completa as etapas e informa 123, Então recebe o recibo.",
                                 "Cenário: OTP incorreto — Quando o usuário informa 000, Então o pagamento não é concluído.",
                                 "Cenário: desistência — Quando o usuário recusa o carrinho, Então nenhum Payment Mandate é criado.",
                                 "Os mandates da compra concluída aparecem em ap2_env_mandates com environment='v4'.",
                                 "Com um 503 simulado na primeira chamada do Shopping Agent v1 ao modelo, a conversa continua após a nova tentativa."],
                      pts=8, deps=["F-V4.3.1", "F-V4.2.1"],
                      tasks=[("Back", "Iniciar o ADK Web restrito ao Shopping Agent v1", "Conforme decisão do spike.", "/dev-ui público lista só shopping_agent.", 5),
                             ("Infra", "Rota e limite de requisições do ADK Web no nginx", "location dedicada com limit_req.", "429 acima do limite.", 3),
                             ("Back", "Persistir os mandates da jornada assistida no Supabase", "Garantir o espelhamento dos arquivos gerados pelo v1.", "Linhas com environment='v4'.", 5),
                             ("Back", "Alinhar o RetryingLlmAgent do Shopping Agent v1 à regra de retry da v2", "Até 2 novas tentativas só em 503/UNAVAILABLE, com espera crescente.", "Teste unitário com 503 simulado.", 3),
                             ("QA", "Executar os cenários de compra assistida", "Com evidências e consumo do Gemini registrado.", "Evidências anexadas.", 5)]),
             ]),
    ]))

# ============================ v5 — Jornada assistida no web client =========
EPICS.append(dict(
    id="EP-V5", version="v5", branch="homolog-v5", base="homolog-v4",
    title="v5 · Jornada assistida (human-present) no web client React",
    contexto=("O web client publicado (code/web-client) só suporta a jornada autônoma do Shopping Agent v2 (FLOW card ou x402). "
              "A jornada assistida da v4 roda no ADK Web, que é uma tela de desenvolvimento."),
    objetivo="Oferecer no mesmo web client as duas jornadas do AP2 — autônoma (human-not-present) e assistida (human-present) — para comparação lado a lado.",
    incluido=["Branch homolog-v5, Space ap2-homolog-v5 e projeto Vercel ap2-homolog-v5-frontend.",
              "Escolha da jornada na tela inicial.", "Telas da jornada assistida: opções de compra, forma de pagamento e Payment Mandate na Trusted Surface, OTP e recibo.",
              "Protocolo de integração entre web client e Shopping Agent v1 (definido em spike)."],
    excluido=["App Android (v6).", "Troca de moeda para BRL (pendência P8.1)."],
    metrica=["Compra assistida concluída pelo web client em 3 execuções seguidas.",
             "Compra autônoma continua passando no roteiro de regressão no mesmo web client."],
    dependencias=["Épico v4 concluído.", "Tradução pt-BR do web client: PR #5 aprovado no teste de aceitação da interface em 27/09/2026, com ajustes pedidos (aviso de manter a aba aberta, mensagem de erro legível, rótulo do cartão no recibo). Mesclar antes do EP-V5 para evitar conflito de textos."],
    riscos=["O Shopping Agent v1 responde em texto livre para o ADK Web; a tela React precisa de artifacts estruturados.",
            "Os textos da tela podem conflitar com a tradução pt-BR se forem feitos em paralelo."],
    premissas=["O Shopping Agent v1 pode ser exposto por A2A (get_fast_api_app com a2a=True) como a v2; confirmar no spike."],
    features=[
        env_feature("v5", "homolog-v4", "F-V5.1", vercel=True),
        dict(id="F-V5.2", title="Integração do web client com o Shopping Agent v1",
             problema="O web client só conhece o protocolo e os artifacts do Shopping Agent v2.",
             solucao="Expor o Shopping Agent v1 por A2A com artifacts estruturados e configurar a URL no web client (VITE_ASSISTED_AGENT_URL).",
             usuarios="Pessoas que validam a jornada assistida.",
             rns=["RN01 – A jornada autônoma não muda.", "RN02 – A URL do agente da jornada assistida vem de variável VITE_*."],
             fora=["Mudança nos mandates do AP2."], deps=["F-V5.1 concluída."],
             criterios=["O web client envia uma mensagem ao Shopping Agent v1 e exibe a resposta.",
                        "Com o agente da jornada assistida fora do ar, a tela mostra erro e a jornada autônoma continua disponível."],
             pbis=[
                 dict(id="F-V5.2.1", title="Spike: protocolo entre web client e Shopping Agent v1",
                      como="time de desenvolvimento", quero="definir como o web client conversa com o Shopping Agent v1",
                      para="reaproveitar o cliente A2A existente e receber dados estruturados",
                      contexto="O web client usa A2A message/stream (a2aClient.ts). O v1 hoje é servido pelo ADK Web.",
                      rns=["RN01 – Decisão registrada no CLAUDE.md."], fora=["Implementação das telas."],
                      criterios=["Documento com o contrato dos artifacts (tipos e campos) de cada etapa da jornada assistida.",
                                 "Prova de conceito recebendo o primeiro artifact no web client."],
                      pts=3, deps=["F-V5.1.1"],
                      tasks=[("Back", "Avaliar expor o Shopping Agent v1 por A2A com run_server próprio", "Prova de conceito com get_fast_api_app(a2a=True).", "Agent card do v1 responde.", 5),
                             ("Front", "Avaliar o reaproveitamento de a2aClient.ts para o v1", "Mapear diferenças de artifacts.", "Lista de diferenças registrada.", 3),
                             ("Docs", "Registrar o contrato de artifacts da jornada assistida", "Tipos e campos de cada etapa.", "Contrato revisado.", 2)]),
                 dict(id="F-V5.2.2", title="Escolha entre jornada autônoma e assistida na tela inicial",
                      como="pessoa que valida o AP2", quero="escolher a jornada antes de iniciar a conversa",
                      para="testar as duas no mesmo endereço",
                      contexto="Hoje a tela abre direto na jornada autônoma.",
                      rns=["RN01 – A escolha fica visível durante toda a conversa.", "RN02 – Trocar de jornada inicia nova conversa."],
                      fora=["Salvar preferência do usuário."],
                      criterios=["A tela inicial mostra as duas opções com uma descrição curta de cada.",
                                 "Ao escolher a assistida, as mensagens vão para o Shopping Agent v1.",
                                 "Ao trocar de jornada no meio da conversa, a tela pede confirmação e inicia nova sessão."],
                      pts=3, deps=["F-V5.2.1"],
                      tasks=[("Front", "Criar seletor de jornada e roteamento de agente", "Usar VITE_AGENT_URL e VITE_ASSISTED_AGENT_URL.", "Mensagens chegam ao agente certo.", 5),
                             ("Infra", "Cadastrar VITE_ASSISTED_AGENT_URL no projeto Vercel da v5", "Variável e novo deploy.", "Bundle contém a URL.", 1),
                             ("QA", "Testar troca de jornada e regressão da autônoma", "Executar critérios e roteiro da v2.", "Evidências anexadas.", 3)]),
             ]),
        dict(id="F-V5.3", title="Telas da jornada assistida no web client",
             problema="As etapas de confirmação da jornada assistida não têm tela no web client.",
             solucao="Criar os cartões de cada etapa (fatiamento por passo do fluxo), reaproveitando o padrão visual da Trusted Surface da v2.",
             usuarios="Pessoas que validam a jornada assistida.",
             rns=["RN01 – Cada etapa exige ação explícita do usuário.", "RN02 – O Payment Mandate é assinado na Trusted Surface.",
                  "RN03 – Valores em USD, exibidos como US$ 0,00."],
             fora=["Endereço de entrega real.", "Conversão de moeda."], deps=["F-V5.2 concluída."],
             criterios=["Compra assistida concluída pela tela com OTP 123.",
                        "Recusa em qualquer etapa encerra a compra sem Payment Mandate."],
             pbis=[
                 dict(id="F-V5.3.1", title="Seleção das opções de compra do Merchant",
                      como="usuário da jornada assistida", quero="ver as opções de compra retornadas pelo Merchant e escolher uma",
                      para="confirmar o que vou comprar",
                      contexto="O Merchant Agent devolve opções assinadas (v3).",
                      rns=["RN01 – A tela mostra nome, preço e comerciante de cada opção.", "RN02 – Só uma opção pode ser escolhida."],
                      fora=["Filtros e ordenação."],
                      criterios=["A tela lista as opções recebidas com nome, preço e comerciante.",
                                 "Ao escolher uma opção, a escolha é enviada ao agente e a próxima etapa aparece.",
                                 "Sem opções retornadas, a tela mostra mensagem e permite refazer o pedido."],
                      pts=5, deps=["F-V5.2.2"],
                      tasks=[("Front", "Criar o cartão de opções de compra", "Componente e tipo do artifact.", "Cartão renderiza os dados do contrato.", 5),
                             ("Back", "Emitir o artifact de opções no Shopping Agent v1", "Conforme contrato do spike.", "Artifact recebido pela tela.", 5),
                             ("QA", "Testar seleção e lista vazia", "Critérios de aceite.", "Evidências anexadas.", 3)]),
                 dict(id="F-V5.3.2", title="Escolha da forma de pagamento e assinatura do Payment Mandate na Trusted Surface",
                      como="usuário da jornada assistida", quero="escolher a forma de pagamento e assinar o Payment Mandate",
                      para="autorizar exatamente o pagamento que vi na tela",
                      contexto="O Credentials Provider Agent lista as formas de pagamento (v4). Na v2 a Trusted Surface assina open mandates; aqui assina o Payment Mandate da compra.",
                      rns=["RN01 – A Trusted Surface mostra item, valor, comerciante e forma de pagamento antes de assinar.",
                           "RN02 – Sem assinatura, nenhum pagamento é iniciado."],
                      fora=["Troca de forma de pagamento depois de assinar."],
                      criterios=["A tela lista as formas de pagamento da conta de demonstração.",
                                 "A Trusted Surface mostra item, valor, comerciante e forma de pagamento.",
                                 "Ao recusar, a compra é encerrada e nenhum Payment Mandate é criado.",
                                 "Ao assinar, o Payment Mandate aparece na aba Mandates."],
                      pts=8, deps=["F-V5.3.1"],
                      tasks=[("Front", "Criar o cartão de formas de pagamento", "Lista e seleção.", "Seleção enviada ao agente.", 5),
                             ("Front", "Adaptar a Trusted Surface para o Payment Mandate da jornada assistida", "Reaproveitar MandateApproval.", "Assinatura gera o mandate.", 8),
                             ("Back", "Emitir os artifacts de formas de pagamento e de pedido de assinatura", "Conforme contrato.", "Artifacts recebidos pela tela.", 5),
                             ("QA", "Testar assinatura e recusa", "Critérios de aceite.", "Evidências anexadas.", 3)]),
                 dict(id="F-V5.3.3", title="Desafio OTP e recibo da compra assistida",
                      como="usuário da jornada assistida", quero="informar o OTP e ver o recibo",
                      para="concluir o pagamento e ter a confirmação",
                      contexto="O Processor Agent pede OTP (demo 123) antes de concluir.",
                      rns=["RN01 – O campo OTP aceita só dígitos.", "RN02 – (Proposta, não vem do repositório; confirmar com o PO) Após 3 OTPs errados, a compra é encerrada."],
                      fora=["Reenvio de OTP."],
                      criterios=["Com OTP 123, a tela mostra o recibo com número do pedido, valor e forma de pagamento.",
                                 "Com OTP errado, a tela mostra erro e permite nova tentativa.",
                                 "(Se RN02 for confirmada) Após 3 OTPs errados, a compra é encerrada sem cobrança."],
                      pts=5, deps=["F-V5.3.2"],
                      tasks=[("Front", "Criar o cartão de OTP e reaproveitar o ReceiptCard", "Campo, validação e envio.", "Recibo exibido.", 5),
                             ("Back", "Aplicar o limite de tentativas de OTP (se RN02 for confirmada)", "Verificar se o Processor Agent já limita tentativas; implementar só após confirmação da regra.", "Quarta tentativa recusada.", 3),
                             ("QA", "Testar OTP correto, errado e limite", "Critérios de aceite + consumo do Gemini.", "Evidências anexadas.", 3)]),
             ]),
    ]))

# ============================ v6 — Go e Android =============================
EPICS.append(dict(
    id="EP-V6", version="v6", branch="homolog-v6", base="homolog-v5",
    title="v6 · Agentes em Go e app Android de demonstração",
    contexto=("O repositório tem dois exemplos fora do Python: code/samples/go (Merchant, Credentials Provider e Processor em Go para o cenário "
              "human-present/cards, com o Shopping Agent Python) e code/samples/android (app Android de compras com Digital Payment Credentials, "
              "que usa Merchant e Credentials Provider Python nas portas 8001/8002 via `adb reverse`). O app lê GEMINI_API_KEY do local.properties "
              "e grava a chave no BuildConfig, e usa URLs http://localhost fixas."),
    objetivo="Permitir validar o cenário assistido com backend em Go e distribuir um APK de homologação que usa o backend público.",
    incluido=["Branch homolog-v6 e Space ap2-homolog-v6.", "Build e execução dos agentes Go no container, com seleção Python × Go.",
              "App Android com URL do backend configurável e sem chave do Gemini no APK.", "APK de homologação publicado no GitHub Releases."],
    excluido=["Publicação na Google Play.", "Versão iOS."],
    metrica=["Compra assistida concluída com backend Go em 3 execuções seguidas.",
             "APK de homologação instalado em aparelho físico concluindo uma compra com DPC."],
    dependencias=["Épico v5 concluído (jornada assistida).", "Aparelho Android compatível com Credential Manager/DPC para o teste.",
                  "Certificado de demonstração do DPC (certs/ds_cert_sdjwt.pem) disponível no backend."],
    riscos=["Uma chave do Gemini dentro do APK fica exposta a qualquer pessoa que instalar o app.",
            "O Credentials Provider do cenário Android usa chave pública do Agent Provider extraída do certificado DPC; pode conflitar com a configuração da v4/v5."],
    premissas=["Os agentes Go chamam ou não o Gemini — verificar no código antes de estimar o consumo.",
               "O app aceita trocar as URLs em tempo de build ou na tela de configurações (SettingsScreen.kt usa constante)."],
    features=[
        env_feature("v6", "homolog-v5", "F-V6.1"),
        dict(id="F-V6.2", title="Agentes Go como backend alternativo do cenário assistido",
             problema="Os agentes Go só rodam localmente com run.sh.",
             solucao="Compilar os agentes Go no Dockerfile (estágio de build Go) e escolher o backend por AP2_BACKEND_LANG=python|go.",
             usuarios="Desenvolvedores que comparam implementações.",
             rns=["RN01 – Padrão python; go só quando configurado.", "RN02 – Mesmas portas e rotas (8001–8003)."],
             fora=["Reescrita do Shopping Agent em Go."], deps=["F-V6.1 concluída."],
             criterios=["Com AP2_BACKEND_LANG=go, os agent cards de 8001–8003 são servidos pelos binários Go.",
                        "A compra assistida conclui com backend Go."],
             pbis=[
                 dict(id="F-V6.2.1", title="Binários Go no container com seleção de backend",
                      como="responsável pela homologação", quero="trocar o backend do cenário assistido para Go por variável",
                      para="comparar comportamento e consumo entre Python e Go",
                      contexto="code/samples/go tem Makefile com `make build` e cmd/ com os entry points.",
                      rns=["RN01 – Build Go em estágio separado do Dockerfile; imagem final só com os binários."],
                      fora=["Otimização de imagem."],
                      criterios=["O build do Space conclui com os binários Go.",
                                 "Com AP2_BACKEND_LANG=go, o log mostra os agentes Go iniciados.",
                                 "Com valor inválido, o container usa python e registra aviso."],
                      pts=5, deps=["F-V6.1.1"],
                      tasks=[("Infra", "Adicionar estágio de build Go ao Dockerfile", "Multi-stage com `make build`.", "Binários na imagem final.", 5),
                             ("Back", "Selecionar Python ou Go no start.sh por AP2_BACKEND_LANG", "Iniciar os processos do backend escolhido.", "Log mostra a escolha.", 3),
                             ("QA", "Testar os três valores de AP2_BACKEND_LANG", "python, go e inválido.", "Evidências anexadas.", 2)]),
                 dict(id="F-V6.2.2", title="Compra assistida com backend Go",
                      como="pessoa que valida o AP2", quero="concluir a compra assistida com o backend Go",
                      para="confirmar interoperabilidade A2A/AP2 entre Python e Go",
                      contexto="O Shopping Agent v1 (Python) conversa com Merchant/CP/Processor em Go.",
                      rns=["RN01 – Mesmo roteiro da v4/v5."], fora=["Diferenças de texto entre implementações."],
                      criterios=["Compra concluída com OTP 123 e recibo.", "Mandates registrados com environment='v6'."],
                      pts=5, deps=["F-V6.2.1"],
                      tasks=[("QA", "Executar o roteiro de compra assistida com backend Go", "3 execuções com evidências.", "Evidências anexadas.", 5),
                             ("Docs", "Registrar diferenças observadas entre Python e Go", "Tabela no CLAUDE.md.", "Documento revisado.", 2)]),
             ]),
        dict(id="F-V6.3", title="App Android de homologação usando o backend público",
             problema="O app só funciona com o aparelho ligado por USB (adb reverse para localhost) e grava a chave do Gemini no APK.",
             solucao="URLs do backend por configuração de build, chamadas HTTPS ao Space, chamadas ao Gemini via backend e APK publicado no GitHub Releases por workflow.",
             usuarios="Pessoas que validam a jornada com Digital Payment Credentials no celular.",
             rns=["RN01 – Nenhuma chave de API dentro do APK.", "RN02 – Só HTTPS para o backend.", "RN03 – APK de homologação assinado com chave de debug/homologação, não de produção."],
             fora=["Google Play.", "Suporte a aparelhos sem Credential Manager/DPC."], deps=["F-V6.1 concluída."],
             criterios=["O APK publicado não contém a string da chave do Gemini (verificação por análise do APK).",
                        "O app conclui uma compra com DPC usando o backend público da v6."],
             pbis=[
                 dict(id="F-V6.3.1", title="App Android configurado para o backend público sem chave no APK",
                      como="pessoa que valida no celular", quero="usar o app sem cabo USB e sem chave embutida",
                      para="testar de qualquer lugar sem expor a chave do Gemini",
                      contexto="SettingsScreen.kt e ShoppingTools.kt usam http://localhost:8001/8002; ChatRepository.kt usa BuildConfig.GEMINI_API_KEY.",
                      rns=["RN01 – URLs do Merchant e do Credentials Provider vêm do build (gradle) ou da tela de configurações.",
                           "RN02 – As chamadas ao Gemini passam por um endpoint do backend com limite de requisições."],
                      fora=["Login do usuário no app."],
                      criterios=["Com o APK instalado, o app se conecta ao Space da v6 por HTTPS.",
                                 "O APK não contém a chave do Gemini.",
                                 "Com o backend fora do ar, o app mostra erro de conexão."],
                      pts=8, deps=["F-V6.1.1"],
                      tasks=[("Mobile", "Parametrizar as URLs do backend no build do app", "buildConfigField para MERCHANT_URL e CP_URL.", "App usa as URLs do build.", 5),
                             ("Back", "Criar endpoint de proxy do Gemini para o app, com limite de requisições", "Rota no Space que usa GOOGLE_API_KEY do servidor.", "App conversa sem chave local.", 8),
                             ("Mobile", "Trocar a chamada direta ao Gemini pelo proxy", "Alterar ChatRepository.kt.", "Nenhuma referência a GEMINI_API_KEY no APK.", 5),
                             ("Segurança", "Verificar o APK contra segredos embutidos", "Análise do APK (apktool/strings).", "Relatório anexado.", 2),
                             ("Infra", "Expor as rotas do Merchant e do Credentials Provider do cenário Android no nginx", "Com limite de requisições.", "Rotas respondem por HTTPS.", 3)]),
                 dict(id="F-V6.3.2", title="APK de homologação publicado no GitHub Releases",
                      como="pessoa que valida no celular", quero="baixar o APK da versão",
                      para="instalar sem Android Studio",
                      contexto="Hoje o app só é gerado pelo Android Studio.",
                      rns=["RN01 – Cada release v6.x publica um APK com o número da versão.", "RN02 – O workflow não usa segredos além dos necessários para assinar o APK de homologação."],
                      fora=["Atualização automática do app."],
                      criterios=["Um push de tag v6.* gera o APK no GitHub Releases.",
                                 "O APK instala em aparelho físico e abre a tela inicial.",
                                 "Uma compra com DPC é concluída em aparelho físico compatível."],
                      pts=5, deps=["F-V6.3.1"],
                      tasks=[("Infra", "Criar workflow de build do APK (Gradle) e publicação no Releases", "GitHub Actions com JDK e Android SDK.", "APK anexado à release.", 5),
                             ("QA", "Testar instalação e compra com DPC em aparelho físico", "Registrar modelo e versão do Android.", "Evidências anexadas.", 5),
                             ("Docs", "Escrever instruções de instalação do APK de homologação", "README do exemplo Android.", "Instruções revisadas.", 2)]),
             ]),
    ]))
